language: python

matrix:
    include:
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7

before_install:
    - pip install -r requirements.txt

script:
    - flake8 tlv8
    - coverage run -m unittest tests/

after_success:
    - coveralls